version: '2.1' 
services: 
  nodejs_80: 
    image: nodejs80/node80 
    build: ./test_80
    container_name: nodejs_80 
    ports: 
      - 8080:8080
    restart: on-failure
  nodejs_81: 
    image: nodejs81/node81 
    build: ./test_81
    container_name: nodejs_81 
    ports: 
      - 8081:8081
    restart: on-failure
