version: "3"
services:
  nodejs:
    build:
	context: .
	dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ./:/home/docker/nodejs
      - node_modules:/home/docker/nodejs/module/.bin/nodemon
    expose:
      - "8081"
    command: index.js

